window_profiles:
- difficulty_level: "large"
  R_train: 64
  R_val: 16
  R_test: 16
  M: 2048
  L_H: [64, 128]
  L_rec: [64, 128]
  L_roll: [128, 256]
- difficulty_level: "medium"
  R_train: 32
  R_val: 8
  R_test: 8
  M: 1024
  L_H: [16, 32, 64]
  L_rec: [16, 32, 64]
  L_roll: [64, 128]
- difficulty_level: "small"
  R_train: 16
  R_val: 4
  R_test: 4
  M: 256
  L_H: [16]
  L_rec: [16]
  L_roll: [32]